
require 'google-search/item/base'
require 'google-search/item/web'
require 'google-search/item/blog'
require 'google-search/item/book'
require 'google-search/item/image'
require 'google-search/item/local'
require 'google-search/item/news'
require 'google-search/item/video'
require 'google-search/item/patent'
