#!/bin/zsh

source ~/.zshrc;


#########################
# Contants.
#########################
VPREFS="${HOME}/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/"
NVPREFS="${HOME}/Library/Application Support/Alfred 2/Workflow Data/"

###############################################################################
# Read the bundleid from the workflow's info.plist
###############################################################################
getBundleId() {
  /usr/libexec/PlistBuddy  -c "Print :bundleid" "info.plist"
}

###############################################################################
# Get the workflow data dir
###############################################################################
getDataDir() {
  local BUNDLEID=$(getBundleId)
  echo "${NVPREFS}${BUNDLEID}"
}

if [ ! -d "$(getDataDir)" ]; then
   mkdir -p "$(getDataDir)";
   touch "$(getDataDir)/s3basename.txt";
fi

#
# Get the s3 base directory name stored.
#
DirName=`cat "$(getDataDir)/s3basename.txt"`;

cdir="${@[1]}";
scriptDir=`pwd`;

#
# Go to the directory with the videos.
#
cd $cdir;

#
# Get the name without the path.
#
vdirName="${cdir##*/}";

echo "Copying files from $cdir to $DirName/$vdirName."

s3cmd put $vdirName-*.(mov|mp4) "$DirName/$vdirName/" ;

echo "All Done! ";

