# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "plist", ">=3.1.0"
gem "logging", ">=1.8.0"

gem "guard"
gem "guard-rspec", ">=0", :group => [:development, :test]
gem "guard-bundler", ">=0", :group => [:development, :test]
gem "hoe-gemspec", ">=0", :group => [:development, :test]
gem "rb-fsevent", "~>0.9", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", ">=0", :group => [:development, :test]
gem "terminal-notifier-guard", ">=0", :group => [:development, :test]
gem "rake", ">=10.0.0", :group => [:development, :test]
gem "rspec", ">=2.13", :group => [:development, :test]
gem "hoe-bundler", ">=0", :group => [:development, :test]
gem "hoe-version", ">=0", :group => [:development, :test]
gem "growl", ">=0", :group => [:development, :test]
gem "hoe-git", ">=0", :group => [:development, :test]

# vim: syntax=ruby
